version: "3"

services:
  app:
    container_name: finder-api
    build: ./backend/
    environment:
      REDIS_HOST: redis_cache
    depends_on:
      - redis_cache
    ports:
      - "45678:45678"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis_cache:
    container_name: redis-cache
    image: redis:latest
    command: "redis-server --maxmemory 8gb --maxmemory-policy allkeys-lru --save 36000 1 1200 500000"
    ports:
      - "6380:6379"
    volumes:
      - "./redis-data/:/data/"
