version: "3"

services:
    app:
        container_name: finder-api
        build: ./backend/
        environment:
            REDIS_HOST: redis_cache
        depends_on:
            - redis_cache
        ports:
            - "45678:45678"
        extra_hosts:
            - "host.docker.internal:host-gateway"

    redis_cache:
        container_name: redis-cache
        image: redis:latest
        ports:
            - "6380:6379"
        volumes:
            - "./redis-data/:/data/"
    client:
        container_name: finder-client
        build: ./frontend/
        ports:
          - '8080:3000'
        volumes:
          - ./frontend:/app
          - /app/node_modules
        stdin_open: true
        tty: true