[project]

name = "wikipathfinder"
version = "0.2"
description = "Wiki game solution implementation."
authors = [
    {name = "Anton Sharov"}
]
dependencies = [
    "aiohttp",
    "fastapi[all]",
    "redis>=5"
]
